Ilmastokompassi/Ilmastokompassi

- documentation/workflow_guide.md
also tested that pushing works
> edited workflow document

- .github/workflows/main.yml
Actions for CI, setting up Python environment, installing Poetry version 1.6.1 and running tests
> Setting up first version of GitHub Actions

- documentation/workflow_guide.md
> 'skip ci' added to documentation

- README.md
> Updating README.md to English

- frontend/.eslintrc.cjs
- frontend/.prettierignore
- frontend/.prettierrc.json
- frontend/README.md
- frontend/index.html
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.css
- frontend/src/App.jsx
- frontend/src/index.css
- frontend/src/main.jsx
- frontend/vite.config.js
> Added prettier

- .github/workflows/main.yml
> Updating CI GitHub Actions

- .github/labeler.yml
- .github/workflows/labeler.yml
Add workflow to automate some of the PR labeling.
> Add PR labeler workflow

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- frontend/src/App.jsx
- frontend/src/theme.jsx
This PR is mostly indented to test the new frontend workflow.
> Add ThemeProvider sample and fix/test CI/CD

- frontend/src/components/Navbar.jsx
- frontend/src/components/Survey.jsx
- frontend/src/pages/SurveyPage.jsx
- frontend/src/router.jsx
Adding survey page with preliminary elements, adding route to /survey
> Adding survey page

- frontend/src/components/Question.jsx
localStorage allows us to maintain user's progress through the survey, fixing previous issue that user's answers were not saved when switching between questions.
> Added functions to handle answer saving locally

- frontend/package-lock.json
- frontend/package.json
- frontend/src/tests/questionPage.test.js
Added dependency jest-fetch-mock so that the current tests for question use mocked API calls. These are not final tests by any means, just showcasing how tests could be done.
> Adding tests for rendering individual question

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
This PR will adds trigger GitHub Actions workflows to test and publish images intended for production deployment.
> Add workflow trigger for GitHub releases

- frontend/src/components/Navbar.jsx
Removed the unnecessary Kysymys tab from the navbar. Made the Ilmastokompassi header fit better on mobile screen.
> Feature navbar fixes

- frontend/cypress/e2e/spec.cy.js
- frontend/src/components/Navbar.jsx
> Cypress test to navigate pages

- frontend/src/components/Navbar.jsx
- frontend/src/pages/ClimateProfilePage.jsx
- frontend/src/router.jsx
> ClimateProfilesPage and navbar to page done

- documentation/database.md
> Add initial database documentation

- backend/src/schema.sql
- documentation/database.md
Adds schema.sql to backend/src directory.
Contributes to #142
> Creating schema.sql for database schema

- frontend/src/components/ClimateProfile.jsx
- frontend/src/pages/ClimateProfilePage.jsx
> ClimateProfile page contains name, desc, pic

- frontend/src/components/ClimateProfile.jsx
- frontend/src/pages/ClimateProfilePage.jsx
> Climateprofilepage correct order

- backend/.pylintrc
- backend/poetry.lock
- backend/poetry.toml
- backend/pyproject.toml
- backend/src/__init__.py
- backend/src/app.py
- backend/src/config.py
- backend/src/extensions.py
- backend/src/routes.py
- backend/src/tests/config.py
- backend/src/tests/test_app.py
- backend/src/tests/test_db.py
This PR changes Flask backend to:
- [Use App factory pattern](https://flask.palletsprojects.com/en/2.3.x/patterns/appfactories/)
- Add's missing python-dotenv and pull flask configuration from environment variables if available.
> Restructure Flask application to be more suitable for testing database

- backend/src/schema.sql
changed order & removed an extra comma
> sql schema to right format to work in postgres

- backend/src/repositories/profile_repository.py
- backend/src/schema.sql
- frontend/src/pages/ClimateProfilePage.jsx
profile backend info is through to frontend climate profile page
> Feature frontend profile fetchs

- documentation/environment_setup_workflow.md
Adding guide how to setup database locally. 
Contributes to #142
> Update environment setup workflow

- documentation/environment_setup_workflow.md
> Minor changes to environment setup workflow

- documentation/environment_setup_workflow.md
Added instruction to create questions database
> Update environment_setup_workflow.md [skip ci]

- frontend/src/components/ClimateProfile.jsx
- frontend/src/pages/ClimateProfilePage.jsx
> Better ui for profilepage

- backend/src/routes.py
- frontend/src/components/QuestionCard.jsx
- frontend/src/pages/QuestionPage.jsx
Created new route that handles submitting answers to database. Added id and name parameters to options for better submit functionality.
Contributes to #143 as this pull request doesn't include tests.
> User's answers are saved to database after submit

- frontend/src/components/QuestionCard.jsx
- frontend/src/pages/QuestionPage.jsx
Changed the layout  of the question pages to be more responsive on different screens. Took material UI components to better use, implementing stack elements and defining them by MUI standards. Closes #182
> better ui layout for question pages

- frontend/src/components/Navbar.jsx
- frontend/src/pages/OwnClimateProfilePage.jsx
- frontend/src/pages/QuestionPage.jsx
- frontend/src/router.jsx
User gets pop up alert for successful answer submission and is directed to new /profile page. Added /profile to navbar as 'Ilmastoprofiili'.
Contributes to #188
> Feedback for succesful answer submission, redirect to /profile

- frontend/src/pages/SummaryPage.jsx
Added styling to summary page that uses similar styling as Climate profile page. Also page content is currently hardcoded.
Contributes to #188
> Styling for summary page

- frontend/cypress/e2e/summary.cy.js
Added preliminary Cypress tests for summary page as these will change after Tuesday's customer meeting 100 %.
Contributes to #188
> Cypress tests for summary page

- backend/src/tests/test_profile_repository.py
> Tests for profile_repository

- documentation/kubernetes.md
> Add secret configuration to the docs

- frontend/src/components/Navbar.jsx
- frontend/src/pages/ClimateProfilePage.jsx
- frontend/src/pages/SurveyPage.jsx
- frontend/src/theme.jsx
If usage of custom breakpoints like this is not optimal, can be tweaked later.
> create breakpoints and apply on navbar, fix surveypage alignment

- documentation/architecture.md
> Add initial Kubernetes architecture diagram

- frontend/src/components/ClimateProfile.jsx
- frontend/src/pages/ClimateProfilePage.jsx
- frontend/src/pages/LandingPage.jsx
Changed fontSize breakpoints to be uniform throughout the application
> Application's typography font size breakpoints are uniform

- frontend/src/pages/SurveyPage.jsx
This PR fixes survey page's heading font size and removes smileys from button.
> Adding fontSize breakpoints to survey page and changing button text

- frontend/src/pages/QuestionPage.jsx
> Navigate to next question automatically

- .github/workflows/frontend.yml
This PR adds `npm run test` to frontend workflow to ensure we run tests for submitted code.
> Adding npm run test to frontend workflow

- frontend/src/pages/QuestionPage.jsx
> Arrow navigation survey

- frontend/src/components/QuestionCard.jsx
- frontend/src/pages/QuestionPage.jsx
Fixed question cards stretching when question is multiple lines long. Centered question cards on survey page.
Closes #221
> Question position stays same

- backend/src/schema.sql
- documentation/database.md
> Update schema for the group functionality

- frontend/src/pages/QuestionPage.jsx
> Fixed navigation bug

- backend/src/repositories/group_repository.py
- backend/src/routes.py
- backend/src/services/group_service.py
- frontend/src/components/FormDialog.jsx
> Group questions can only be made if group exists

- backend/src/services/survey_service.py
- backend/src/tests/test_survey_service.py
> Surveyservice tests

- frontend/src/components/FormDialog.jsx
> Group adding in uppercase

- frontend/src/components/SummaryProfile.jsx
- frontend/src/pages/SummaryPage.jsx
Summarypage calculates your most accurate climate profile based on your answer scores. Other profiles and respective scores can be added if needed.  Also created component SummaryProfile for usage on the page.
Contributes to #236
> Summarypage calculates profile

- frontend/cypress/e2e/groupCreation.cy.js
- frontend/cypress/e2e/groupJoining.cy.js
- frontend/src/components/FormDialog.jsx
- frontend/src/components/GroupDialog.jsx
This pull requests add E2E tests for joining group session. We still need to add testing for successful joining to an actually existing group.
Contributes to #227
> E2E tests for joining group session

- frontend/cypress/e2e/groupCreation.cy.js
- frontend/cypress/e2e/groupJoining.cy.js
- frontend/cypress/support/commands.js
- frontend/src/components/Navbar.jsx
> Create more tests for joining group and refactoring

- backend/src/tests/test_group_service.py
- backend/src/tests/test_survey_service.py
This pull request makes `survey_service.py` and `group_service.py` have 100% test coverage.
> Service test coverage to 100%

- frontend/src/components/SummaryPie.jsx
- frontend/src/pages/SummaryPage.jsx
Increase pie legend font size and add some padding to summary page. Second try :sweat_smile:
> increase pie legend font size and add some padding to summarypage

- backend/poetry.lock
- backend/pyproject.toml
- backend/src/api.py
- backend/src/questions.sql
- backend/src/tests/test_app.py
> Test to api.py

- frontend/cypress/e2e/summary.cy.js
- frontend/cypress/e2e/survey.spec.cy.js
- frontend/src/hooks/useTitle.js
- frontend/src/pages/ClimateProfilePage.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/pages/QuestionPage.jsx
- frontend/src/pages/SummaryPage.jsx
- frontend/src/pages/SurveyPage.jsx
Let's keep it DRY and hide the annoying `useEffect` inside a new `useTitle` hook. Also made the page title keep track, which question is currently selected.
> Use useTitle hook

- frontend/src/components/ClimateProfile.jsx
- frontend/src/components/FormDialog.jsx
- frontend/src/components/SummaryProfile.jsx
- frontend/src/pages/SummaryPage.jsx
- frontend/src/pages/SurveyPage.jsx
Adds Card component to `SurveyPage.jsx` to avoid text being hidden by background.
Removing borderRadius from `ClimateProfile.jsx` as Card borderRadius' needs to be same for all pages.  
<div> to React Fragment in  `FormDialog.jsx` as it broke content inside Card component.
> Card component to SurveyPage

- frontend/.eslintrc.cjs
- frontend/src/components/SummaryDoughnut.jsx
- frontend/src/pages/SummaryPage.jsx
> change summary doughnut numbers to add to 100.

- frontend/src/components/SummaryProfile.jsx
> Climate Profiles shown horizontal on summary page

- frontend/src/components/SummaryProfile.jsx
- frontend/src/pages/SummaryPage.jsx
> Summary page shows multiple profiles and it looks good

- frontend/cypress/e2e/climateProfiles.cy.js
- frontend/cypress/e2e/groupCreation.cy.js
- frontend/cypress/e2e/groupJoining.cy.js
- frontend/cypress/e2e/navBar.spec.cy.js
- frontend/cypress/e2e/summary.cy.js
- frontend/cypress/e2e/survey.spec.cy.js
- frontend/src/components/FormDialog.jsx
- frontend/src/components/GroupDialog.jsx
- frontend/src/components/Navbar.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/pages/QuestionPage.jsx
- frontend/src/pages/SummaryPage.jsx
- frontend/src/pages/SurveyPage.jsx
- frontend/src/router.jsx
- frontend/src/tests/components/Navbar.test.js
- frontend/src/tests/questionPage.test.js
- frontend/src/tests/surveyPage.test.js
This pull request changes all frontend route names from English to Finnish and fixes all the broken references caused by the change.
Closes #322
> Changing frontend route names to Finnish

- frontend/src/components/QuestionCard.jsx
- frontend/src/pages/FactQuizQuestionPage.jsx
- frontend/src/pages/QuestionPage.jsx
- frontend/src/router.jsx
- frontend/src/tests/components/QuestionCard.test.js
- frontend/src/tests/questionPage.test.js
> created template for quiz

- backend/src/api.py
- backend/src/repositories/group_repository.py
- backend/src/services/group_service.py
- frontend/src/pages/SummaryPage.jsx
> Group data is shown in summary page

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
VSCode is the de-facto IDE used by the current development team. This PR adds project-wide default configurations to use autopep8 & prettier for the lint each document when saved.
> Add project-wide .vscode configurations

- frontend/cypress/e2e/surveySwipe.cy.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/QuestionPage.jsx
Formatter not formatting again :D but no biggie
Closes #325 
Closes #313
> add cypress tests for swipe

- backend/src/repositories/quiz.repository.py
- backend/src/repositories/quiz_repository.py
- backend/src/services/quiz_service.py
- backend/src/tests/test_quiz_service.py
Preliminary versions of `QuizRepository` and `QuizService` classes are added in this pull request. The classes will be shaped further as the development progresses.
Also includes 100% coverage tests for `quiz_service.py`
Contributes to #239 
Closes #326
> Add QuizRepository and QuizService classes

- backend/src/api.py
- backend/src/quiz_questions.sql
- backend/src/repositories/quiz_repository.py
- backend/src/services/quiz_service.py
- backend/src/tests/test_quiz_service.py
- frontend/src/pages/FactQuizQuestionPage.jsx
- Fact quiz questions can be fetched from backend (database) and are shown in the frontend.
- Quiz answers are saved to database.
Closes #309
Closes #340 
Contributes #239 
Contributes #310
Contributes #312
> Quiz repo enhancement

- frontend/cypress/e2e/navBar.spec.cy.js
- frontend/src/components/Navbar.jsx
Couldn't test locally, lets see what CI tests say.
> Add link to group summary in navbar

- frontend/cypress/e2e/groupCreation.cy.js
- frontend/cypress/e2e/groupJoining.cy.js
- frontend/cypress/e2e/survey.spec.cy.js
- frontend/cypress/support/commands.js
- frontend/src/components/GroupDialog.jsx
- frontend/src/components/GroupSummaryDialog.jsx
- frontend/src/pages/GroupSummaryPage.jsx
> Links to groupsummary

- frontend/src/components/GroupDialog.jsx
> console error fixed by deleting unneccessary parameter

- .gitignore
- backend/src/api.py
- backend/src/repositories/quiz_repository.py
- backend/src/services/quiz_service.py
- frontend/src/pages/FactQuizQuestionPage.jsx
Contributes #239
Contributes #310
> backend returns list of correct answers

- backend/src/api.py
- backend/src/repositories/quiz_repository.py
- backend/src/services/quiz_service.py
> info text is delivered with correct answers

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- README.md
- kubernetes/production/kustomization.yaml
- kubernetes/production/patch-ingress.yaml
- kubernetes/staging/kustomization.yaml
- kubernetes/staging/patch-ingress.yaml
* Production: https://ilmastokompassi.it.helsinki.fi
* Staging: https://ilmastokompassi-staging.it.helsinki.fi
> Configure the new staging and production hostnames

- backend/migrations/04-quiz_questions.sql
- frontend/src/components/QuizQuestionCard.jsx
- frontend/src/pages/FactQuizQuestionPage.jsx
After answering:
- Line over wrong options
- Answers marked right/wrong
Contributes #312 
Closes #364
> Show feedback on quiz answers

- frontend/src/components/QuizQuestionCard.jsx
> Checkmarks are only displayed on selected answer options

- frontend/src/components/Navbar.jsx
> Add frontpage link to ClimComp logo

- frontend/src/pages/FactQuizQuestionPage.jsx
> Swipeable factquiz

- frontend/src/components/GroupDialog.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/theme.jsx
New functionalitys for front page. Needs work on mobile.
Luo ryhmä- button should be removed from SurveyPage. This needs changes to cypress tests.
> Restructuring front page

- frontend/cypress/e2e/groupCreation.cy.js
- frontend/cypress/e2e/groupJoining.cy.js
- frontend/cypress/support/commands.js
- frontend/src/pages/LandingPage.jsx
- frontend/src/pages/SurveyPage.jsx
- frontend/src/tests/surveyPage.test.js
Made cahnges to surveypage, cypress tests, jest tests and success message on landing page.
> Cypress tests made after restructuring of landing page

- frontend/src/components/CorrectAnswersInfo.jsx
- frontend/src/components/FactInfoBox.jsx
- frontend/src/components/QuizQuestionCard.jsx
- frontend/src/pages/FactQuizQuestionPage.jsx
- Components in fact quiz page have same width now.
- Show correct answer count
> Refactored fact quiz, added correct answer count

- frontend/src/pages/LandingPage.jsx
- frontend/src/theme.jsx
Works on mobile and computer.
Cotributes #375
> Landing page refactoring

- frontend/cypress/e2e/navBar.spec.cy.js
- frontend/cypress/e2e/survey.spec.cy.js
- frontend/src/components/Navbar.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/pages/SurveyPage.jsx
- frontend/src/router.jsx
- frontend/src/tests/components/Navbar.test.js
- frontend/src/tests/surveyPage.test.js
..page and needed test changes.
Intro text about the survey and about doing it as a group. Link to survey questions. Changed the name of the survey to Ilmastoroolikysely, and made changes to the links and page names and navbar accordingly. Updated cypress and jest tests.
> Ilmastoroolikysely page layout, re-routing after changes in name of .. 

- frontend/src/components/GroupDialog.jsx
- frontend/src/components/Navbar.jsx
- frontend/src/pages/SurveyPage.jsx
Shows only when user is not in a group
> added join group form to surveypage

- frontend/src/pages/SurveyPage.jsx
Changes made to Ilmastoroolikysely page.
> changed start button to card component &  other tweaks.

- frontend/cypress/e2e/groupCreation.cy.js
- frontend/cypress/e2e/groupJoining.cy.js
- frontend/cypress/e2e/survey.spec.cy.js
- frontend/cypress/support/commands.js
> [!IMPORTANT]
> Reset the database before and after each testing with `bin/db-reset`
Closes #376 
Closes #305
> Updated cypress test to use database

- frontend/cypress/e2e/factQuiz.cy.js
> Add Cypress E2E tests for fact quiz

- frontend/cypress/e2e/survey.spec.cy.js
- frontend/src/pages/SummaryPage.jsx
> Zero corner case for summary page

- backend/src/repositories/quiz_repository.py
- backend/src/services/quiz_service.py
- backend/src/tests/test_quiz_service.py
> Add quiz service tests to backend

- frontend/src/components/Navbar.jsx
- frontend/src/pages/FaqPage.jsx
- frontend/src/router.jsx
- frontend/src/tests/components/Navbar.test.js
Closes #373 
FAQ in navbar, content to page and test to find this page in navbar.
> FaqPage for Ilmastokompassi

- frontend/cypress/e2e/groupCreation.cy.js
- frontend/cypress/e2e/groupJoining.cy.js
- frontend/src/components/JoinGroup.jsx
- frontend/src/components/Navbar.jsx
> Refactor the group joining cypress tests & component

- backend/src/api.py
- backend/src/tests/test_api.py
- frontend/cypress/support/commands.js
- frontend/src/components/CreateGroupDialog.jsx
- frontend/src/components/JoinGroup.jsx
* Follow REST API convention by changing `/api/new-group` to `/api/group/new`
* Misc. group creation dialog refactoring
* `GroupDialog.jsx` -> `CreateGroupDialog.jsx`
> Refactor create group dialog

- frontend/src/components/SummaryDoughnut.jsx
- frontend/src/pages/SummaryPage.jsx
> Make the chart.js doughnut responsive

- frontend/src/components/SummaryRole.jsx
- frontend/src/pages/GroupSummaryPage.jsx
- frontend/src/pages/SummaryPage.jsx
-cypress tests will need to be edited to match this
> describing texts now the same on both pages, profiili mentions -> rooli

- frontend/src/components/ToSurveyCard.jsx
- frontend/src/pages/LandingPage.jsx
Responsive template for landing page cards.
Contributes #375
> Landingpage survey and quiz cards

- frontend/src/components/JoinGroup.jsx
- frontend/src/components/ToSurveyCard.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/pages/SurveyPage.jsx
* Refine and simplify landing page layout logic
* Move ``CreateGroupDialog`` component out of the ``JoinGroup`` component
> Refine landing page cards

- frontend/src/pages/FactQuizSummaryPage.jsx
> Quiz summary UI

- frontend/src/pages/FactQuizQuestionPage.jsx
> Quiz does not stick to navbar in mobile view

- frontend/src/components/NavigationBar.jsx
- frontend/src/components/SummaryDoughnut.jsx
- frontend/src/pages/FactQuizSummaryPage.jsx
- frontend/src/pages/QuestionPage.jsx
Added labels to group icon in navbar, the progress bar of the survey, and the summary donut. Also added a title to the fact quiz recap page. Part of #369
> Accessibility missing labels

- frontend/cypress/e2e/factQuiz.cy.js
> start the test from landing page

- frontend/src/components/CreateGroupDialog.jsx
- frontend/src/components/JoinGroup.jsx
> pressing enter in input fields works

- frontend/src/components/NavigationBar.jsx
> Fix the group menu regression

- frontend/cypress/e2e/factQuiz.cy.js
- frontend/src/pages/FactQuizQuestionPage.jsx
- frontend/src/pages/FactQuizSummaryPage.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/router.jsx
> Change refences from tietovisa to oppimisvisa

- frontend/cypress/e2e/groupJoining.cy.js
- frontend/cypress/e2e/groupSummary.cy.js
- frontend/cypress/e2e/navigationBar.spec.cy.js
- frontend/src/components/NavigationBar.jsx
> Added link to frontpage to hamburger, tests to fit the change

- frontend/cypress/e2e/navigationBar.spec.cy.js
- frontend/src/components/NavigationBar.jsx
> factquiz added to navbar and cypress test

- frontend/src/components/RoleQuestionButtons.jsx
- frontend/src/components/SurveyQuestionCard.jsx
- frontend/src/pages/QuestionPage.jsx
Closes #448 
Arrow buttons are inside card.
I left the progress bar outside.
> Arrow_buttons_visible_new_component

- frontend/src/components/RoleQuestionButtons.jsx
- frontend/src/pages/RoleSurveyPage.jsx
- frontend/src/pages/RoleSurveyQuestionPage.jsx
- frontend/src/router.jsx
* Renamed `SurveyPage` -> `RoleSurveyPage`
* Renamed `QuestionPage` -> `RoleSurveyQuestionPage`
* Removed unnecessary `isLastQuestion` parameter from `RoleSurveyButtons`
* Removed some unnecessary card styles to keep it consistent with rest of the theme.
> Fix role survey buttons

- frontend/cypress/e2e/groupSummary.cy.js
- frontend/cypress/index.d.ts
:tada:
Closes #306 
Closes #260
> Finish group summary role cypress tests

- frontend/src/components/JoinGroup.jsx
- frontend/src/components/JoinGroupForm.jsx
- frontend/src/pages/RoleSurveyPage.jsx
This fixes current cypress test fails.
> Move Snackbar to its default position to avoid covering elements

- frontend/src/components/QuizQuestionCard.jsx
- frontend/src/utils/shuffleArray.js
- Created and placed shulffleArray function in utils
> Fact quiz options are shuffled

- frontend/src/components/Footer.jsx
- frontend/src/components/Layout.jsx
Just add placeholder for the footer.
Contributes to #450
> Lay groundwork for the footer

- frontend/cypress/e2e/factQuiz.cy.js
- frontend/src/components/factQuiz/QuizQuestionCard.jsx
- frontend/src/theme.jsx
Cypress tests that check the color
Contributes #434
> Show gray markers for options that were not selected

- frontend/src/components/factQuiz/QuizQuestionCard.jsx
- frontend/src/pages/FactQuizQuestionPage.jsx
Also moved question / totalquestions inside card
Contributes #434
> progressbar for oppimisvisa

- frontend/cypress/e2e/factQuiz.cy.js
- frontend/src/pages/FactQuizSummaryPage.jsx
- A card as the base of the layout 
- added the quiz picture
- added customers text additions to the page
- adjusted cypress tests to the changed text
> factquiz summarypage layout fixed and text by customer added

- frontend/src/components/ToSurveyCard.jsx
- frontend/src/pages/LandingPage.jsx
- Removed card element from behind the header and subheader elements.
- Adjusted image and text scaling on factQuiz and roleSurvey cards
- Inserted new enhanced description texts
Do not get too distracted by the current fontSize breakpoints, these have to be further discussed between the project team on last week of sprint. Updating this information to the task as well.
Contributes to #453
> Further adjustments to front page visual elements

- kubernetes/base/backend/deployment.yaml
> Ensure backend deployment fails if initContainer fails

- backend/src/routes/quiz_routes.py
- frontend/cypress/e2e/factQuiz.cy.js
- frontend/src/pages/FactQuizQuestionPage.jsx
- New api route for fetching just the correct answers
- Selected answers are stored in localstorage for now
- Previously answered questions are disabled and answers are shown
- Cypress tests
Closes #456
> User can see what they answered in previous questions

- frontend/src/components/factQuiz/QuizQuestionCard.jsx
- frontend/src/components/roleSurvey/RoleQuestionButtons.jsx
- frontend/src/components/roleSurvey/SurveyQuestionCard.jsx
- frontend/src/pages/FactQuizQuestionPage.jsx
- frontend/src/pages/RoleSurveyQuestionPage.jsx
- frontend/src/tests/components/SurveyQuestionCard.test.js
Adjusted the card sizes as well as the button sizes. Also refactored the structure of both cards, as they were not optimal. Now both quizzes look similar and have mostly the same amount of padding etc.
Closes #513 
Contributes to #447
> Refactor Quiz- and Surveypage question cards to be uniform and look nice

- backend/src/repositories/quiz_repository.py
- backend/src/services/quiz_service.py
- backend/src/tests/test_quiz_service.py
- frontend/cypress/e2e/factQuiz.cy.js
- frontend/src/components/factQuiz/QuizSummaryAccordion.jsx
- frontend/src/pages/FactQuizSummaryPage.jsx
- infotext is fetched from the backend and shown in the frontend
- updated tests
> Add info quiz summary

- frontend/src/components/roleSurvey/SurveyQuestionCard.jsx
> Display answer options in reverse order on mobile viewports

- frontend/src/components/roleSurvey/SummaryDoughnut.jsx
- frontend/src/components/roleSurvey/SurveyQuestionCard.jsx
- frontend/src/pages/FactQuizSummaryPage.jsx
- frontend/src/pages/FaqPage.jsx
- frontend/src/pages/RoleSurveyGroupSummaryPage.jsx
- frontend/src/pages/RoleSurveyQuestionPage.jsx
- frontend/src/pages/RoleSurveySummaryPage.jsx
- frontend/src/tests/components/SurveyQuestionCard.test.js
Closes #447 
This also fixes console errors for rolesummarypage and jest-tests had some errors as well.
> Every page refactoring, fix jest-test and console error

- frontend/src/components/Background.jsx
- frontend/src/components/NavigationBar.jsx
> Fix to background image jumping

- frontend/src/components/Layout.jsx
Change minHeight back to 100hv. Did not fix the bug on mobile. Created additional bugs on desktop.
> Changed layout height to 100vh

- frontend/cypress/e2e/footerBar.cy.js
- frontend/src/components/Footer.jsx
> Removed 2023 from footer

- frontend/src/components/ToSurveyCard.jsx
- frontend/src/components/factQuiz/CorrectAnswersInfo.jsx
- frontend/src/components/factQuiz/FactInfoBox.jsx
- frontend/src/components/factQuiz/QuizSummaryAccordion.jsx
- frontend/src/components/roleSurvey/GroupAccordion.jsx
- frontend/src/components/roleSurvey/RoleAccordion.jsx
- frontend/src/components/roleSurvey/RoleQuestionButtons.jsx
- frontend/src/components/roleSurvey/SummaryRole.jsx
- frontend/src/pages/FactQuizSummaryPage.jsx
- frontend/src/pages/FaqPage.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/pages/RoleSurveyGroupSummaryPage.jsx
- frontend/src/pages/RoleSurveyPage.jsx
- frontend/src/pages/RoleSurveySummaryPage.jsx
- frontend/src/theme.jsx
- Fixed arrow button colour to have a lighter disabled colour
- Added padding to summary pages in the role cards
- Uniform style of cards with rounded corners and elevation
- Transparent background to the header text on the frontpage to make it more readable
Closes #541
> Layout fixes

- frontend/src/components/ToSurveyCard.jsx
These fixes might or might not work, they have to be literally tested in production :D the changes don't affect the site on other browsers, so in the worst case, nothing changes.
> Add a few sx properties that might fix problem on safari

- backend/src/repositories/group_repository.py
- backend/src/repositories/profile_repository.py
- backend/src/repositories/quiz_repository.py
- backend/src/repositories/survey_repository.py
- backend/src/routes/quiz_routes.py
- backend/src/services/quiz_service.py
- backend/src/services/survey_service.py
- backend/src/tests/test_group_service.py
- backend/src/tests/test_profile_service.py
- backend/src/tests/test_quiz_routes.py
- backend/src/tests/test_quiz_service.py
- backend/src/tests/test_survey_service.py
- frontend/cypress/e2e/factQuiz.cy.js
- frontend/src/components/factQuiz/CorrectAnswersInfo.jsx
- frontend/src/components/factQuiz/QuizQuestionCard.jsx
- frontend/src/pages/FactQuizQuestionPage.jsx
This PR loads the fact quiz state from the server instead of storing it in the localStorage. Includes misc. refactoring all around the codebase.
Closes #535
> Get fact quiz state from backend
