backend/src/routes.py
frontend/.dockerignore
frontend/Dockerfile
frontend/src/pages/LandingPage.jsx
frontend/vite.config.js

* Add dockerfile for frontend project. First build step builds the React app and in second we copy it into unprivileged NGINX container for the actual deployment.
* Configured Vite to proxy the requests to ``localhost:5173/api`` -> ``localhost:5000/api`` in the local development environment.
Closes #71

Add Dockerfile for frontend project

---

frontend/Dockerfile

Use [``npm ci``](https://docs.npmjs.com/cli/v10/commands/npm-ci?v=true) instead of ``npm install`` in the frontend Dockerfile

Use npm ci in the Dockerfile

---

kubernetes/base/kustomization.yaml
kubernetes/production/kustomization.yaml
kubernetes/staging/add-backend-imagestream-trigger.yaml
kubernetes/staging/add-frontend-imagestream-trigger.yaml
kubernetes/staging/enable-imagestream-lookup.yaml
kubernetes/staging/imagestreams.yaml
kubernetes/staging/kustomization.yaml

This PR adds OpenShift specific configuration for the staging environment to automatically redeploy the containers with new images, when a new image tagged with `latest` is pushed to the Docker Hub.

Fix automatic redeployment for the staging environment

---

backend/Dockerfile
kubernetes/base/backend/deployment.yaml

* Configure environment variables for the `backend` container pods from `Secret` object.
* Add `libpq-dev` to backend Dockerfile
Secrets are now deployed to staging and production environment.
Closes #132 
Contributes to #164

Configure backend for database deployment

---

backend/Dockerfile

* Use latest bookworm in the backend Dockerfile in both builder and runtime stages

Use latest debian in backend Dockerfile

---

frontend/src/components/FormDialog.jsx
frontend/src/pages/SummaryPage.jsx

Also added to summary page an if-clause, that hides the climate profile details if the survey is not answered.  This will be useful when the one who creates a group gets redirected to the summary page before they / anyone has answered a survey.

group option saves token in frontend and moves to survey

---

frontend/src/pages/QuestionPage.jsx

This pull request adds 0.5 second delay before redirecting user to next question after selecting answer option. Increases user experience as users' can visibly see that the selected option is actually selected.
Closes #251

Adding small delay after selecting answer option

---

backend/src/repositories/group_repository.py
backend/src/routes.py
backend/src/services/group_service.py
frontend/src/components/GroupDialog.jsx
frontend/src/pages/SurveyPage.jsx

This pull request adds new `GroupDialog` component that handles creating new group. We have also added `GroupRepository`, `GroupService` and routing to make all this handling possible.
Submission validation and restrictions are not handled, these needs have been mentioned in issue #231.
Contributes to #229 and #231

Create new group

---

frontend/src/components/GroupDialog.jsx

While user writes group session id they see it in uppercase in dialog window and group session id will be also saved to database in uppercase.
Contributes to #231

Group name is saved in uppercase and user sees name written in uppercase

---

backend/src/routes.py
backend/src/services/group_service.py
backend/src/tests/test_group_service.py
frontend/src/components/GroupDialog.jsx

Frontend and backend group name (token) validations added. There is preliminary tests for backend validation, no frontend tests implemented yet.
Known issue that needs to be fixed later: Frontend doesn't inform user, if group name (token) already exists in the database. Group name (token) should be unique.
Contributes to #232 and #232

Validate group 

---

frontend/src/components/Navbar.jsx

Wanted to remove error caused by missing group avatar element on navbar. Decided to change the icon from letter 'R' (which came from MUI placeholder) to a group icon and remove unnecessary tooltip.

change group icon and remove tooltip

---

.github/labeler.yml

- Shortened one of the labels a bit
- Removed `ci/cd` label from k8s, 'twas technically incorrect.

Update labeler actions workflow

---

frontend/src/components/SummaryProfile.jsx
frontend/src/pages/SummaryPage.jsx

All content on `SummaryPage` is inside a single Card -component, all text is now visible on white background

Moving Card -component to whole SummaryPage content

---

frontend/src/pages/FactQuizQuestionPage.jsx

`FactQuizQuestionPage.jsx` had reference to `/quiztest/`, changing it to `/tietovisa/`

Fix path reference to '/tietovisa/ from '/quiztest/'

---

backend/src/repositories/quiz_repository.py
frontend/cypress/e2e/survey.spec.cy.js
frontend/src/components/QuestionCard.jsx
frontend/src/pages/FactQuizQuestionPage.jsx

- Answer selections are reset when moving to next question
- `Vastaa` button is disabled, if no answers are selected
- After pressing `Vastaa` button, `Seuraava kysymys` button is displayed and user can move to next question
- After pressing `Vastaa` button on the last question, `Lopeta kysely` button is displayed instead of `Seuraava kysymys` button
This pull request has functionality that interacts with the backend but we have not built the backend side yet.
Please note that `quiz_repository.py` involves comment about need to create response id on quiz start, we can not do it on every questions like the current code does it.
Contributes to #239

Restructured how the fact quiz works

---

backend/src/api.py
backend/src/repositories/group_repository.py
backend/src/services/group_service.py
frontend/src/pages/SummaryPage.jsx

Auto refresh:
- Summary page updates every 15 seconds with SWR, if there is a groupToken to show the up to date group results.
Hidden responses:
- Changed SQL command to contain response_id as well.  Group service counts the different response_ids and returns the length, aka the amount of different people who have answered.
- The response amount is used in Summary page, where it works as a condition to not show the group statistic block if there is less than 5 answers.

Summarypage: group statistics: -hidden if < 5 responses & -auto refresh

---

backend/src/api.py
frontend/src/components/GroupSummaryDialog.jsx
frontend/src/pages/GroupSummaryPage.jsx
frontend/src/pages/SurveyPage.jsx
frontend/src/router.jsx
frontend/src/tests/surveyPage.test.js

Created separate page to view group summary statistics. Added button in "kysely"-page, to access the group statistic page without doing a survey.

Group link to group summary page

---

frontend/src/pages/QuestionPage.jsx

Set max width to progress bar, so it doesn't get too wide on a large resolution.

Set max width to progress bar

---

bin/dev
frontend/Dockerfile.dev

We should now handle the common case where changes were made after first run of ``docker compose watch``.

Force a docker compose build before watching for changes

---

frontend/src/components/Navbar.jsx
frontend/src/pages/GroupSummaryPage.jsx

Fragment error fixed in navbar Menu, and padding added to groupsummary to make it look nicer.
Closes #354 & #355

fix fragment error on menu and padding on groupsummary

---

frontend/src/components/Navbar.jsx

The error was the inconsistency of clicking the "ryhmän tiedot". MenuItem was accidentally inside a typography element.

Ryhmän tiedot button in hamburger now always routes to the group summary

---

frontend/src/pages/FactQuizQuestionPage.jsx

`Accordion` -component is displayed after answering question, if the `infoText` is not empty string. Component also renders the fetched info content.
Contributes to #310 and #312

Display infobox after answering

---

frontend/cypress/e2e/groupJoining.cy.js
frontend/src/components/GroupDialog.jsx
frontend/src/components/JoinGroup.jsx
frontend/src/pages/SurveyPage.jsx
frontend/src/tests/surveyPage.test.js

- Made "liity" into a clear button to avoid confusion in joining group.
- Joining group , and creating group components are in a row, but switch to a column on xs screen
- Some wording changes in texts
- added link to ilmastoroolit page from ilmastoroolikysely instead of the placeholder card below the actual content.

ui changes to make group joining a better user experience

---

frontend/cypress/e2e/groupSummary.cy.js
frontend/cypress/index.d.ts
frontend/cypress/support/commands.js

There is some weird Cypress magic happening currently and the group summary page doesn't render climate roles of group, which blocks generating further tests.
Contributes to #306

Add Group summary Cypress tests

---

frontend/src/theme.jsx

Use [MUI's `responsiveFontSizes(theme, responsiveFontSizesOptions)`](https://mui.com/material-ui/customization/theming/#responsivefontsizes-theme-options-theme) to configure its default responsive typography properties at the theme level. 
The default configuraiton scales the typography to be smaller for smaller viewports by a given factor, as seen in the the chart below:
This allows to use semantically correct typography variants which now scale accordingly for smaller viewports.
Contributes to #411

Use MUI provided responsive font size configuration

---

frontend/cypress/e2e/groupSummary.cy.js
frontend/src/components/factQuiz/QuizQuestionCard.jsx

`shuffleArray` is now imported from correct directory.
Removed reference to other climate roles as only **Ilmastoasiantuntija** is rendered and test wouldn't obviously pass otherwise.

Fix import and Cypress test issue

---

frontend/src/components/NavigationBar.jsx
frontend/src/components/ToSurveyCard.jsx
frontend/src/components/roleSurvey/RoleAccordion.jsx
frontend/src/components/roleSurvey/RoleImage.jsx
frontend/src/pages/LandingPage.jsx
frontend/src/pages/RoleSurveyPage.jsx

accessibility testing done through chrome lighthouse. Changes made to: 
- describing alt texts to pictures (and added a picture to rolesurveypage)
- edited aria-labels to function properly 
- Landingpage and Rolesurvey-page: heading levels changed to correct ones, if header is only used for style, the header tag is overridden/hidden by 'div-component' per per Paulus instructions.

Accessibility changes

---

frontend/src/components/NavigationBar.jsx
frontend/src/components/ToSurveyCard.jsx
frontend/src/components/roleSurvey/SummaryRole.jsx
frontend/src/pages/FactQuizSummaryPage.jsx
frontend/src/pages/FaqPage.jsx
frontend/src/pages/LandingPage.jsx
frontend/src/pages/RoleSurveyGroupSummaryPage.jsx
frontend/src/pages/RoleSurveySummaryPage.jsx
frontend/src/theme.jsx

Change the headings on most pages to new ones, so we don't have to use h4-h5. The font sizes are now larger, following the feedback received. 
The font sizes can be altered later if needed, these are the ones I found pleasant enough. The reviewer of this pull request can check the sizes locally if needed. Double checking that both desktop and mobile sizes look nice could be useful.
Contributes to #411

Change heading font sizes to larger ones

---

frontend/cypress/e2e/groupCreation.cy.js
frontend/cypress/e2e/groupSummary.cy.js
frontend/src/components/CreateGroupDialog.jsx
frontend/src/components/GroupForm.jsx
frontend/src/components/roleSurvey/GroupAccordion.jsx
frontend/src/pages/RoleSurveyPage.jsx

- Accordion with all group functions for the role survey on the page
- Layout inside accordion improved: liity moved next to luo ryhmä, and they stay in a row also on a small screen beneath the text field
- Cohesive look on buttons: luo ryhmä, liity, and aloita
- Renamed components to match better the new structure
- Updated cypress tests
closes #511

Group functions moved to accordion and layout improvements, updated cypress

---

backend/src/api.py
backend/src/routes/group_routes.py
backend/src/routes/quiz_routes.py
backend/src/routes/survey_routes.py
backend/src/services/group_service.py
backend/src/services/quiz_service.py
backend/src/services/survey_service.py
backend/src/tests/test_group_routes.py
backend/src/tests/test_quiz_routes.py
backend/src/tests/test_survey_routes.py
frontend/cypress/e2e/groupJoining.cy.js
frontend/cypress/support/commands.js
frontend/src/components/CreateGroupDialog.jsx
frontend/src/components/roleSurvey/GroupAccordion.jsx

* Use [generic error handling](https://flask.palletsprojects.com/en/3.0.x/errorhandling/#generic-exception-handlers) in the API
* Remove incorrectly named and unused `/groups/{groupToken}/survey/summary` endpoint
* Simplify exception raising logic and utilize HTTP status codes better
* Fix group joining cypress tests

Refactor API error handling

---

frontend/src/components/factQuiz/QuizSummaryAccordion.jsx

also removed ":" from oikeat vastaukset
Closes #528

centered subheadings in quiz summary accordions
